import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export const exportToPDF = async (vocab: any[], title: string = "My Japanese Library") => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  const itemsPerPage = 80; // 20 per column, 4 columns
  const totalPages = Math.ceil(vocab.length / itemsPerPage);

  for (let p = 0; p < totalPages; p++) {
    if (p > 0) pdf.addPage();
    
    const pageItems = vocab.slice(p * itemsPerPage, (p + 1) * itemsPerPage);
    const itemsPerCol = Math.ceil(pageItems.length / 4);
    
    const element = document.createElement('div');
    element.style.width = '1200px';
    element.style.padding = '40px';
    element.style.backgroundColor = 'white';
    element.style.color = '#1c1917';
    element.style.fontFamily = 'serif';
    element.style.position = 'absolute';
    element.style.left = '-9999px';

    const header = document.createElement('div');
    header.style.textAlign = 'center';
    header.style.marginBottom = '40px';
    header.style.borderBottom = '1px solid #e7e5e4';
    header.style.paddingBottom = '20px';
    header.innerHTML = `
      <h1 style="font-size: 36px; margin: 0; font-style: italic;">${title}</h1>
      <p style="font-size: 14px; color: #78716c; margin-top: 10px;">Page ${p + 1} of ${totalPages} • Generated by Komorebi</p>
    `;
    element.appendChild(header);

    const grid = document.createElement('div');
    grid.style.display = 'grid';
    grid.style.gridTemplateColumns = 'repeat(4, 1fr)';
    grid.style.gap = '20px';
    
    for (let c = 0; c < 4; c++) {
      const col = document.createElement('div');
      col.style.display = 'flex';
      col.style.flexDirection = 'column';
      col.style.gap = '10px';
      
      const colItems = pageItems.slice(c * itemsPerCol, (c + 1) * itemsPerCol);
      colItems.forEach((item: any) => {
        const row = document.createElement('div');
        row.style.borderBottom = '1px solid #f5f5f4';
        row.style.paddingBottom = '5px';
        row.innerHTML = `
          <div style="font-weight: bold; font-size: 14px;">${item.japanese}</div>
          <div style="font-size: 10px; color: #a8a29e; text-transform: uppercase;">${item.romaji}</div>
          <div style="font-size: 12px; font-style: italic; color: #44403c;">${item.meaning}</div>
        `;
        col.appendChild(row);
      });
      grid.appendChild(col);
    }
    
    element.appendChild(grid);
    document.body.appendChild(element);

    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    pdf.addImage(imgData, 'PNG', 0, 0, pageWidth, pageHeight);
    
    document.body.removeChild(element);
  }

  pdf.save(`${title.toLowerCase().replace(/\s+/g, '-')}-${new Date().getTime()}.pdf`);
};
